### ISSUE TITLE
Have a problem when using LSQ+_V2

### ISSUE THREAD

**Issue by lulululichuan** [ZouJiu1/LSQplus#11]
Hi author, 
    thank you for your great work!
    I meet a problem when using Lsq+_V2:
    `Traceback (most recent call last):
  File "train.py", line 273, in <module>
    train(args)
  File "train.py", line 201, in train
    scaler.scale(loss).backward()
  File "/home/work/ssd1/anaconda3/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/work/ssd1/anaconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function ALSQPlusBackward returned an invalid gradient at index 2 - got [1] but expected shape compatible with [0]`
It seems that the backward func of ALSQPlus has some error, any advice of how to solve this problem?
Thanks in advance!

**Comment by ZouJiu1** [comment]
index 2 is "[return grad_weight, grad_alpha,  None, None, None, grad_beta] " **None**,  it correspond to the "[weight, alpha, g, Qn, Qp, beta]"   **g**,   g have no gradient and it gradient should be None.

**Comment by ZouJiu1** [comment]
It is the answer about backward. [RuntimeError: function ALSQPlusBackward returned a gradient different than None at position](https://blog.csdn.net/m0_50617544/article/details/121312719?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522167773202216800182719218%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fblog.%2522%257D&request_id=167773202216800182719218&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~blog~first_rank_ecpm_v1~rank_v31_ecpm-5-121312719-null-null.blog_rank_default&utm_term=backward&spm=1018.2226.3001.4450)

**Comment by lulululichuan** [comment]
> index 2 is "[return grad_weight, grad_alpha, None, None, None, grad_beta] " **None**, it correspond to the "[weight, alpha, g, Qn, Qp, beta]" **g**, g have no gradient and it gradient should be None.

Yes, I used the code from your repo , and its show that the func of ALSQPlus have the "return grad_weight, grad_alpha, None, None, None, grad_beta" originally.
`class ALSQPlus(Function):
    @staticmethod
    def forward(ctx, weight, alpha, g, Qn, Qp, beta):
        # assert alpha > 0, "alpha={}".format(alpha)
        ctx.save_for_backward(weight, alpha, beta)
        ctx.other = g, Qn, Qp
        w_q = Round.apply(torch.div((weight - beta), alpha).clamp(Qn, Qp))
        w_q = w_q * alpha + beta
        return w_q

    @staticmethod
    def backward(ctx, grad_weight):
        weight, alpha, beta = ctx.saved_tensors
        g, Qn, Qp = ctx.other
        q_w = (weight - beta) / alpha
        smaller = (q_w < Qn).float() #bool值转浮点值，1.0或者0.0
        bigger = (q_w > Qp).float() #bool值转浮点值，1.0或者0.0
        between = 1.0 - smaller -bigger #得到位于量化区间的index
        grad_alpha = ((smaller * Qn + bigger * Qp + 
            between * Round.apply(q_w) - between * q_w)*grad_weight * g).sum().unsqueeze(dim=0)
        grad_beta = ((smaller + bigger) * grad_weight * g).sum().unsqueeze(dim=0)
        #在量化区间之外的值都是常数，故导数也是0
        grad_weight = between * grad_weight
        #返回的梯度要和forward的参数对应起来
        return grad_weight, grad_alpha,  None, None, None, grad_beta`

**Comment by wenpingd** [comment]
> Hi author, thank you for your great work! I meet a problem when using Lsq+_V2: `Traceback (most recent call last): File "train.py", line 273, in <module> train(args) File "train.py", line 201, in train scaler.scale(loss).backward() File "/home/work/ssd1/anaconda3/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/home/work/ssd1/anaconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: Function ALSQPlusBackward returned an invalid gradient at index 2 - got [1] but expected shape compatible with [0]` It seems that the backward func of ALSQPlus has some errors, any advice of how to solve this problem? Thanks in advance!

Hi  lulululichuan, have you solved this problem?

**Comment by MJITG** [comment]
多卡会有这个问题，单卡不会
It occurs when training with multi GPUs and is OK with single GPU

**Comment by sxbkdby8** [comment]
> 多卡会有这个问题，单卡不会 It occurs when training with multi GPUs and is OK with single GPU



> > Hi author, thank you for your great work! I meet a problem when using Lsq+_V2: `Traceback (most recent call last): File "train.py", line 273, in <module> train(args) File "train.py", line 201, in train scaler.scale(loss).backward() File "/home/work/ssd1/anaconda3/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/home/work/ssd1/anaconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: Function ALSQPlusBackward returned an invalid gradient at index 2 - got [1] but expected shape compatible with [0]` It seems that the backward func of ALSQPlus has some errors, any advice of how to solve this problem? Thanks in advance!
> 
> Hi lulululichuan, have you solved this problem?

您好，请问您解决这个问题了嘛
